import { Inter } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/utils/AuthProvider";
import { Toaster } from "react-hot-toast";
import GotoTop from "@/components/GotoTop/GotoTop"
import initTranslations from "../i18n";
import QueryProvider from "@/QueryProvider";
const inter = Inter({ subsets: ["latin-ext"] });
import TranslationsProvider from "@/components/TranslationProvider";
import Massenger from "@/components/Massenger/Massenger";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: {locale}}) {
  const i18NameSpaces = ['common', 'mystuff', 'landing', 'Movies', 'video', 'music', 'series', 'drama', 'channel'];
  const { t, resources } = await initTranslations(locale, i18NameSpaces);
  return (
    <TranslationsProvider resources={resources} locale={locale} namespaces={i18NameSpaces}>
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </head>
      <body >
        <QueryProvider>
          <AuthProvider>
            {children}
            <Toaster
              position="top-right"
              reverseOrder={false}
            />
            <GotoTop />
            <Massenger/>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
    </TranslationsProvider>
  );
}
